// Module:      clk_divider.v
// Project:     MediLink FPGA Emergency Alert Receiver
// Board:       DE10-Lite (MAX 10 FPGA: 10M50DAF484C7G)
// Description: Derives required clocks from the 50 MHz onboard oscillator.
//
//   50 MHz  ──> 25 MHz   (pixel clock for 640x480 @ 60 Hz VGA)
//   50 MHz  ──> 1 kHz    (audio square-wave base for buzzer tone)
//
// Division rationale:
//   25 MHz  : toggle every 1 cycle  -> divide-by-2   counter (1 bit)
//   1 kHz   : toggle every 24999 cycles -> divide-by-50000 counter (16 bit)
//
// All outputs are 50% duty-cycle clock signals generated by toggling a
// register at the appropriate count, which is the safest synthesis-friendly
// approach on MAX 10 (avoids gated-clock issues).


module clk_divider (
    input  wire clk_50mhz,   // 50 MHz system clock from onboard oscillator
    output reg  clk_25mhz,   // 25 MHz pixel clock  (VGA controller)
    output reg  clk_1khz     // 1 kHz audio clock   (alarm driver)
);

    // 25 MHz generation  (divide-by-2)

    // Simply toggle every rising edge of the 50 MHz clock.
    // Result: 50 MHz / 2 = 25 MHz, 50% duty cycle.
    initial clk_25mhz = 1'b0;   // Power-on initialisation (MAX 10 supports this)

    always @(posedge clk_50mhz) begin
        clk_25mhz <= ~clk_25mhz;
    end
    // 1 kHz generation  (divide-by-50,000)
  
    // 50,000,000 Hz / 50,000 = 1,000 Hz
    // Toggle the output every 25,000 cycles -> full period = 50,000 cycles.
    //
    // Counter range: 0 to 24,999  (fits in 15 bits, using 16 for safety)
    //
    // 16-bit counter can hold up to 65,535  (25,000 fits comfortably).

    localparam integer CLK1KHZ_HALF_PERIOD = 25_000 - 1; // Toggle threshold

    reg [15:0] cnt_1khz;

    initial begin
        cnt_1khz  = 16'd0;
        clk_1khz  = 1'b0;
    end

    always @(posedge clk_50mhz) begin
        if (cnt_1khz == CLK1KHZ_HALF_PERIOD) begin
            clk_1khz <= ~clk_1khz;  // Toggle -> completes one half-period
            cnt_1khz <= 16'd0;       // Reset counter
        end else begin
            cnt_1khz <= cnt_1khz + 1'b1;
        end
    end

endmodule